### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by MikaArakawa** [MikaArakawa/furima-35455#22]
# what
S3の導入完了

# why
本番環境での動作確認をするため

# Information

- 自身のフリマアプリのURL
https://furima-35455.herokuapp.com/

- Basic認証のIDとパスワード	
ID:admin 
PW:2222

- 出品者用のメールアドレスとパスワード	
Mail:aaa@aaa
PW:123qwe

- 購入者用のメールアドレスとパスワード	
Mail:bbb@bbb
PW:123qwe

**Comment by takahirohoriguchi** [comment]
レビュー依頼ありがとうございます！
以下コメントしましたので、ご確認をお願いいたします！

**修正点**
・販売手数料 (10%)・販売利益が表示できるようにしましょう。
・商品購入するときにWe're sorryが出ます。購入できるようにしましょう。

**Comment by MikaArakawa** [comment]
# what
S3の導入完了
APIキーの設定をVSCODEに記述

# why
本番環境での動作確認をするため

**Comment by takahirohoriguchi** [comment]
ご提出ありがとうございます！
問題なく正常に動作することが確認できました！　LGTMです✨　
おめでとうございます🎉
